- name: Add clustering features to the feature list
  set_fact:
    extra_features: "{{ extra_features + clustering_features }}"
  when:
   - cluster

- name: Build Karaf feature list
  set_fact:
    features: "{{ default_features + extra_features }}"

- name: Configure ODL Karaf features
  lineinfile:
    dest=/opt/opendaylight/etc/org.apache.karaf.features.cfg
    regexp=^featuresBoot=
    line=featuresBoot={{ features|join(',') }}
    owner=odl
    group=odl
  notify:
    - Stop ODL
    - Cleanup Karaf
    - Start ODL
