---
- include: install_odl.yml
- include: configure_cluster.yml
  when:
   - cluster

- include: configure_karaf_features.yml
- include: configure_nb_rest_port.yml
- include: open_nb_rest_port.yml
- include: start_odl.yml
